name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build images
      run: make build

    - name: Run tests
      run: make test

    - name: Build the Docker image
      run: docker build . --target prod --tag challenge:$(date +%s)
